package quic

import (
	"errors"
	"fmt"
	"net"
	"syscall"

	"github.com/Berserk-Automation-Hub/quic-go-utls/internal/protocol"
	"github.com/Berserk-Automation-Hub/quic-go-utls/internal/utils"
)

//go:generate sh -c "echo '// Code generated by go generate. DO NOT EDIT.\n// Source: sys_conn_buffers.go\n' > sys_conn_buffers_write.go && sed -e 's/SetReadBuffer/SetWriteBuffer/g' -e 's/setReceiveBuffer/setSendBuffer/g' -e 's/inspectReadBuffer/inspectWriteBuffer/g' -e 's/protocol\\.DesiredReceiveBufferSize/protocol\\.DesiredSendBufferSize/g' -e 's/forceSetReceiveBuffer/forceSetSendBuffer/g' -e 's/receive buffer/send buffer/g' sys_conn_buffers.go | sed '/^\\/\\/go:generate/d' >> sys_conn_buffers_write.go"
func setReceiveBuffer(c net.PacketConn) error { return setReceiveBufferTo(c, 0) }

// setReceiveBufferTo raises the socket receive buffer to `want`.
//
// U-LAYER: `want` is tri-state, and the three states are the three things a caller can mean.
//
//	0                     — the caller expressed no opinion: use the package default, which is
//	                        upstream quic-go's behaviour and the zero value of Transport's field.
//	> 0                   — raise the buffer to exactly this, the value the profile declares.
//	UDoNotSetSocketBuffer — the profile declares NO socket buffer. Leave the option at the kernel
//	                        default and issue no setsockopt at all; substituting the library's 7 MB
//	                        for an absent value would be inventing a fingerprint nobody measured.
func setReceiveBufferTo(c net.PacketConn, want int) error {
	if want < 0 {
		return nil
	}
	if want == 0 {
		want = protocol.DesiredReceiveBufferSize
	}
	conn, ok := c.(interface{ SetReadBuffer(int) error })
	if !ok {
		return errors.New("connection doesn't allow setting of receive buffer size. Not a *net.UDPConn?")
	}

	var syscallConn syscall.RawConn
	if sc, ok := c.(interface {
		SyscallConn() (syscall.RawConn, error)
	}); ok {
		var err error
		syscallConn, err = sc.SyscallConn()
		if err != nil {
			syscallConn = nil
		}
	}
	// The connection has a SetReadBuffer method, but we couldn't obtain a syscall.RawConn.
	// This shouldn't happen for a net.UDPConn, but is possible if the connection just implements the
	// net.PacketConn interface and the SetReadBuffer method.
	// We have no way of checking if increasing the buffer size actually worked.
	if syscallConn == nil {
		return conn.SetReadBuffer(want)
	}

	size, err := inspectReadBuffer(syscallConn)
	if err != nil {
		return fmt.Errorf("failed to determine receive buffer size: %w", err)
	}
	if size >= want {
		utils.DefaultLogger.Debugf("Conn has receive buffer of %d kiB (wanted: at least %d kiB)", size/1024, want/1024)
		return nil
	}
	// Ignore the error. We check if we succeeded by querying the buffer size afterward.
	_ = conn.SetReadBuffer(want)
	newSize, err := inspectReadBuffer(syscallConn)
	if newSize < want {
		// Try again with RCVBUFFORCE on Linux
		_ = forceSetReceiveBuffer(syscallConn, want)
		newSize, err = inspectReadBuffer(syscallConn)
		if err != nil {
			return fmt.Errorf("failed to determine receive buffer size: %w", err)
		}
	}
	if err != nil {
		return fmt.Errorf("failed to determine receive buffer size: %w", err)
	}
	if newSize == size {
		return fmt.Errorf("failed to increase receive buffer size (wanted: %d kiB, got %d kiB)", want/1024, newSize/1024)
	}
	if newSize < want {
		return fmt.Errorf("failed to sufficiently increase receive buffer size (was: %d kiB, wanted: %d kiB, got: %d kiB)", size/1024, want/1024, newSize/1024)
	}
	utils.DefaultLogger.Debugf("Increased receive buffer size to %d kiB", newSize/1024)
	return nil
}
